name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t abhiraj405/sms-server .
      - name: Publish Image to dockerhub
        run: docker push abhiraj405/sms-server:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull abhiraj405/sms-server:latest
      - name: Stop and Remove Old Container
        run: docker rm -f mern-sms-server-container
      - name: Run Docker Container
        run: docker run -d -p 5000:5000 --name mern-sms-server-container -e MONGO_URL='${{ secrets.MONGO_URL }}' abhiraj405/sms-server:latest
